link: local
path_home: ${oc.env:HOME}
path_logs: ${oc.env:HOME}
path_od3d: ${oc.env:PIXI_PROJECT_ROOT}/common3d/src/od3d
# path_exps: /scratch/sommerl/exps
path_datasets_raw: /work/dlclarge1/sommerl-od3d/datasets # sshfs maythux@192.168.xx.xx:/home/maythuxServ/Mounted ~/remoteDir
path_datasets_preprocess: /work/dlclarge1/sommerl-od3d/datasets # for student: /misc/student/srinivap/datasets_preprocess
path_exps: ${oc.env:PIXI_PROJECT_ROOT}/experiments
path_cuda: /usr/local/cuda-12.4
url_od3d: git@github.com:GenIntel/common3d.git

install_od3d: False
partition: dllabdlc_gpu-rtx2080

renderer: pytorch3d
